backend_azeri_student/azeri/urls.py
import os
from django.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls.i18n import i18n_patterns  # for url translation
# from oscar.app import application # oscar applications urls here
from django.views.generic import TemplateView
from django.conf.urls import handler404, handler500
from student import views as student_views
from django.urls import path, re_path

admin.autodiscover()

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('labmin/', admin.site.urls),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('page/', include('flatpages.urls')),
    path('faqapi/', include('student.api.urls',namespace='faqapi')),
    #url(r'^api-auth/', include('rest_framework.urls')),

    # url(r'^', include("student.urls")),
    # url(r'^', include("partners.urls")),
]

urlpatterns += [
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name="azeri/robots.txt", content_type='text/plain')),
]


if os.environ.get('PARTNER_PAGE') == "true":
    urlpatterns += [
        path('', include("partners.urls"))
    ]
else:
    urlpatterns += [
        path('', include("student.urls"))
    ]

# urlpatterns += i18n_patterns(
#     url(r'^', include("student.urls")),
#     url(r'^', application.urls),
#     url(r'^page/', include('django.contrib.flatpages.urls')),
# )

handler404 = student_views.error_404
handler500 = student_views.error_500

# in development django built-in server serves static and media content 
if not settings.PROD:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# This is change default admin panel Headers and titles
admin.site.site_header = 'AzeriStudent Admin'
admin.site.site_title = 'AzeriStudent Administration'
admin.site.index_title = 'AzeriStudent Administration'

backend_azeri_student/partners/urls.py
from django.contrib.auth.decorators import permission_required

from partners import views
from django.urls import path, re_path

urlpatterns = [
    path('', views.BaseIndexView.as_view(), name='base_index'),
    path('register/', views.RegisterView.as_view(), name='register_view'),
    path('report/', views.DataAnalysis.as_view(), name='data_analysis'),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('contact/', views.ContactPageView.as_view(), name='contact'),
    re_path(r'^(?P<slug>.*)/$', views.OtherPageView.as_view(), name='other_page_view'),


]

backend_azeri_student/partners/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe

from student.options.fields import YoutubeLinkField
from student.options.tools import get_country_cover, get_slider_image, PARTNER_CONTENT_TYPE, get_event_image, \
    get_partner_says_image, FIRST_CONTENT_TYPE, get_uni_logo


# Create your models here.


class BaseMenu(models.Model):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=255, help_text="Example /about/ -page url")
    order = models.IntegerField(default=0)
    target_blank = models.BooleanField(default=False)
    status = models.BooleanField(default=True)
    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        ordering = ('order',)


class HomePageBaseConfig(models.Model):
    website_title = models.CharField(max_length=255, default="Home page")
    title = models.CharField(max_length=255, default="Home")
    page_url = models.CharField(max_length=255, default="/", help_text="Page url example /about/")
    # social headers
    meta_keywords = models.CharField(max_length=300, editable=False,
                                     default="Azeristudent | You study, we care!")
    meta_description = models.TextField(editable=False,
                                        default="2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.")
    social_image = models.ImageField(upload_to=get_country_cover, null=True, blank=True)
    facebook_social_title = models.CharField(max_length=255, default="Azeristudent | You study, we care!")
    facebook_social_description = models.CharField(max_length=255,
                                                   default="2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.")
    twitter_social_image_alt = models.CharField(max_length=255,
                                                default="2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.")
    twitter_social_creator = models.CharField(max_length=255, default="@azeristudent01")
    twitter_social_site = models.CharField(max_length=255, default="@azeristudent01")
    homepage_title = models.CharField(max_length=255, null=True, blank=True)
    homepage_subtitle = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = "Main page"
        verbose_name_plural = "Main page configurations"


class PartnerSays(models.Model):
    full_name = models.CharField('Full name', max_length=200)
    specialty = models.CharField('Specialty', max_length=250, blank=True, null=True)
    picture = models.ImageField('Picture', upload_to=get_partner_says_image)
    position = models.PositiveIntegerField('Position', default=1)
    text = models.TextField('Text')

    def __str__(self):
        return "{}".format(self.full_name)

    class Meta:
        ordering = ['position']
        verbose_name = 'Partner say'
        verbose_name_plural = 'Partner says'


class Universities(models.Model):
    name = models.CharField(max_length=255)
    university_logo = models.ImageField('Uni_logo', upload_to=get_uni_logo)
    position = models.PositiveIntegerField('Position', default=1)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['position']
        verbose_name = 'University in Exhibition'
        verbose_name_plural = 'Universities in Exhibition'


class RegisterFair(models.Model):
    # deleted 2 fields below
    # first_name = models.CharField('First name', max_length=200, null=True, blank=True)
    # last_name = models.CharField('Last name', max_length=200, null=True, blank=True)
    full_name = models.CharField('Full name', max_length=300)
    reg_loc = models.ForeignKey(BaseMenu, null=True, blank=True, related_name='reg_location', on_delete=models.CASCADE)
    email = models.EmailField('Email Address', max_length=200)
    institution = models.CharField('Institution name', max_length=255)
    message = models.TextField('Special comment')
    billing_address = models.CharField('Billing Address', max_length=255)
    signature = models.CharField('Signature', max_length=200)
    invoice_number = models.CharField('Invoice number', max_length=20, null=True, blank=True)
    # logs
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return "{}".format(self.full_name)


class CitiesTables(models.Model):
    fk = models.ForeignKey(RegisterFair, related_name='cities_tables_register', null=True, on_delete=models.CASCADE)
    cities = models.ForeignKey('EventVideo', related_name='event_cities_tables', null=True, blank=True, on_delete=models.CASCADE)
    table_count = models.PositiveIntegerField('How many tables each city', default=0, validators=[MinValueValidator(0)],
                                              null=True, blank=True)

    def __str__(self):
        return "{}".format(self.fk)

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'


class Programs(models.Model):
    name = models.CharField(max_length=255)
    target_blank = models.BooleanField(default=True)
    link = models.CharField(max_length=255, null=True, blank=True,
                            help_text="Not necessary")

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        verbose_name = 'Program'
        verbose_name_plural = 'Programs'


class EventVideo(models.Model):
    name = models.CharField(max_length=255)
    youtube_link = YoutubeLinkField(null=True, blank=True)
    event_date = models.CharField('Date', max_length=200, null=True, blank=True)
    image = models.ImageField('Image', upload_to=get_event_image, null=True, blank=True)
    position = models.PositiveIntegerField('Position', default=1)
    show_register = models.ManyToManyField(BaseMenu, blank=True)

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        ordering = ['position']
        verbose_name = 'Event'
        verbose_name_plural = 'Events'


class MainPageSlider(models.Model):
    image = models.ImageField(upload_to=get_slider_image, null=True, blank=True)
    youtube_link = YoutubeLinkField(null=True, blank=True)
    home = models.ForeignKey('HomePageBaseConfig', on_delete=models.CASCADE)
    status = models.BooleanField(default=True)

    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s - Slider" % self.image.name


class HomeContent(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    home_content_type = models.IntegerField(choices=PARTNER_CONTENT_TYPE, default=0)
    content = RichTextUploadingField(null=True, blank=True)
    base_home = models.ForeignKey('HomePageBaseConfig', on_delete=models.CASCADE,
                                  null=True, blank=True)
    button_text = models.CharField(max_length=255, null=True, blank=True)
    button_link = models.CharField(max_length=255, null=True, blank=True)
    order = models.IntegerField(default=0,
                                verbose_name="Ordering",
                                help_text="Sorting the content")
    programs = models.ManyToManyField('Programs', blank=True)
    events = models.ManyToManyField('EventVideo', blank=True)
    register_form = models.BooleanField('Register Form', default=False, help_text='if show register form')
    partner_says = models.ManyToManyField('PartnerSays', blank=True)

    # for content_type 0
    left_or_right = models.IntegerField(choices=FIRST_CONTENT_TYPE, null=True, blank=True)
    image = models.FileField(upload_to=get_slider_image, null=True, blank=True)
    universities_from_previous_exhibtions = models.ManyToManyField('Universities', blank=True)

    class Meta:
        ordering = ('order',)


class FooterCopyright(models.Model):
    name = models.CharField(max_length=255, default="&copy; AZERISTUDENT. ALL RIGHTS RESERVED.")

    def __str__(self):
        return "{}".format(self.name)


class EmailList(models.Model):
    email = models.EmailField(max_length=255)

    def __str__(self):
        return "{}".format(self.email)

    class Meta:
        verbose_name = 'Email List'


class Images(models.Model):
    image = models.ImageField('Image', upload_to="Images")
    order = models.PositiveIntegerField(default=1)

    def preview_image(self):
        if self.image:
            return mark_safe(
                "<img style='width:150px' src='{}'/>".format(
                    self.image.url)
            )
        else:
            return ""

    class Meta:
        ordering = ('order',)
        verbose_name = "Images"


class SliderVideo(models.Model):
    youtube_link = YoutubeLinkField(null=True, blank=True)
    status = models.BooleanField(default=True)
    order = models.PositiveIntegerField(default=1)

    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('order',)
        verbose_name = "Videos"

backend_azeri_student/partners/forms.py
from django import forms
from django.forms import formset_factory

from partners.models import RegisterFair, EventVideo, CitiesTables


class RegisterForm(forms.ModelForm):
    # cities = forms.ModelMultipleChoiceField(queryset=EventVideo.objects.filter(show_register=True),
    #                                         widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = RegisterFair
        fields = ['full_name', 'email', 'institution', 'message', 'billing_address', 'signature']
        widgets = {
            'full_name': forms.TextInput(attrs={'placeholder': 'Enter your full name', 'class': 'spring-form-input'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Enter your email address', 'class': 'spring-form-input'}),
            'institution': forms.TextInput(attrs={'placeholder': 'Enter Institution name', 'class': 'spring-form-input'}),
            'message': forms.Textarea(attrs={'placeholder': 'Enter your message', 'class': 'spring-form-input textarea-form'}),
            'billing_address': forms.TextInput(attrs={'placeholder': 'Enter billing address', 'class': 'spring-form-input'}),
            'signature': forms.TextInput(attrs={'placeholder': 'Enter your signature', 'class': 'spring-form-input'}),
        }


class CitiesTableForm(forms.ModelForm):

    class Meta:
        model = CitiesTables
        fields = ['cities', 'table_count']
        widgets = {
            # 'table_count': forms.NumberInput(attrs={'class': 'nonform', 'disabled': 'disabled', 'min': 1})
            'table_count': forms.NumberInput(attrs={'class': 'amount', 'disabled': 'disabled', 'min': 1})
        }


CityFormSet = formset_factory(CitiesTableForm, extra=10)

backend_azeri_student/partners/templates/partners/home/index.html
{% extends 'partners/base/index.html' %}
{% load static %}
{% load partner_filter i18n %}
{% block meta_tags %}
    <meta name="keywords" content="{{ object.meta_keywords }}">
    <meta name="description" content="{{ object.meta_description }}">
{% endblock meta_tags %}
{% block social_headers %}
    <!-- Facebook share header -->
    <meta property="og:title" content="{{ object.facebook_social_title }}">
    <meta property="og:description" content="{{ object.facebook_social_description }}">
    {% if object.social_image %}
        <meta property="og:image"
              content="{{ request.build_absolute_uri|slice:":-1" }}{{ object.social_image.url }}">
    {% endif %}
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <!--Twitter header-->
    <meta name="twitter:card" content="summary_large_image">
    {% if object.social_image %}
        <meta name="twitter:image"
              content="{{ request.build_absolute_uri|slice:":-1" }}{{ object.social_image.url }}">
    {% endif %}
    <meta name="twitter:image:alt" content="{{ object.twitter_social_image_alt }}">
    <meta name="twitter:creator" content="{{ object.twitter_social_creator }}"/>
    <meta name="twitter:site" content="{{ object.twitter_social_site }}">
{% endblock social_headers %}
{% block content %}
    <div id="homepage_section">
        <div class="container">
            <div class="homepage">
                <div class="row">
                    <div class="col-lg-6">
                        {% get_home_page as home_page %}
                        <h3>
                            {{ home_page.homepage_title }}
                        </h3>
                        <p>
                            {{ home_page.homepage_subtitle }}
                        </p>
                        <a href="{{ sing_up_link }}" class="button-a">Sign up</a>
                    </div>
                    <div class="col-lg-6">
                        {% for slider in object.mainpageslider_set.all %}
                            {% if slider.status %}
                                <div class="homepage-video">
                                {% if slider.youtube_link %}
                                    <a data-fancybox="gallery"
                                        href="https://www.youtube.com/embed/{{ slider.youtube_link.get_youtube_id }}?enablejsapi=1&version=3&playerapiid=ytplayer&rel=0&amp;autoplay=1&mute=1">
                                        <i class="fas fa-play"></i>
                                        <img src="{{ slider.youtube_link.get_background_image }}">
                                    </a>
                                {% endif %}
                                </div>
                            {% endif %}
                        {% endfor %}
                </div>
            </div>
        </div>
        <div class="homepage_about">
            <div class="container">
                <div class="row">
                    {% for content in object.homecontent_set.all %}
                        <div class="col-lg-6">
                            <h3>
                                {{ content.title }}
                            </h3>
                            <div class="homepage_about_child">
                               {% if content.home_content_type == 0 %} {# Bir kontentli #}
                                   {{ content.content|safe }}
                                   {% elif content.home_content_type == 1 %} {# Proqramlar #}
                                        <ul>
                                            {% for program in content.programs.all %}
                                                <li>
                                                    <div class="disk_home"></div>
                                                    {{ program.name }}
                                                </li>
                                            {% endfor %}
                                        </ul>
                               {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}