backend_azeri_student/azeri/urls.py
import os
from django.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls.i18n import i18n_patterns  # for url translation
# from oscar.app import application # oscar applications urls here
from django.views.generic import TemplateView
from django.conf.urls import handler404, handler500
from student import views as student_views
from django.urls import path, re_path

admin.autodiscover()

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('labmin/', admin.site.urls),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('page/', include('flatpages.urls')),
    path('faqapi/', include('student.api.urls',namespace='faqapi')),
    #url(r'^api-auth/', include('rest_framework.urls')),

    # url(r'^', include("student.urls")),
    # url(r'^', include("partners.urls")),
]

urlpatterns += [
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name="azeri/robots.txt", content_type='text/plain')),
]


if os.environ.get('PARTNER_PAGE') == "true":
    urlpatterns += [
        path('', include("partners.urls"))
    ]
else:
    urlpatterns += [
        path('', include("student.urls"))
    ]

# urlpatterns += i18n_patterns(
#     url(r'^', include("student.urls")),
#     url(r'^', application.urls),
#     url(r'^page/', include('django.contrib.flatpages.urls')),
# )

handler404 = student_views.error_404
handler500 = student_views.error_500

# in development django built-in server serves static and media content 
if not settings.PROD:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# This is change default admin panel Headers and titles
admin.site.site_header = 'AzeriStudent Admin'
admin.site.site_title = 'AzeriStudent Administration'
admin.site.index_title = 'AzeriStudent Administration'

backend_azeri_student/student/api/urls.py
from django.urls import include
from .views import *
from django.urls import path

app_name='faqapi'
urlpatterns = [
    path('question-type/', FaqQuestionTypeView.as_view(), name = 'question type'),
    path('questions/', FaqQuestionView.as_view(), name = 'question'),
]

backend_azeri_student/student/urls.py
from django.contrib.auth.decorators import permission_required
from django.contrib.sitemaps.views import sitemap

from partners.views import DataAnalysis
from student.sitemaps import *
from student.views import InsuranceView
from . import views
from django.urls import path, re_path

sitemaps = {
    'home': BaseIndexSitemap,
    'about': AboutPageSitemap,
    'country': CountryDetailSitemap,
    'services': ServicesListSitemap,
    'service': ServicesDetailSitemap,
    'news': NewsListSitemap,
    'new': NewsDetailSitemap,
    'blogs': BlogListSitemap,
    'blog':  BlogDetailSitemap,
    'reviews': ReviewListSitemap,
    'review': ReviewDetailSitemap,
    'events': EventListSitemap,
    'event': EventDetailSitemap,
    'reserve': ReserveDateSitemap,
    'university': UniversityDetailSitemap,
    'programs': ProgramsListSitemap,
    'exhibition': ExhibitionDetailSitemap,
    'insurance': InsuranceSitemap,
    'education-category-list': EducationCategoryListSitemap,
}


urlpatterns = [
    # main page home
    path('', views.BaseIndexView.as_view(), name="index"),
    re_path(r'^sitemap\.xml/$', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    # about page
    path('about/', views.AboutPageView.as_view(), name="about-us"),
    # country detail page
    path('countries/<slug:slug>/', views.CountryDetailView.as_view(), name="country-detail"),
    # ajax urls here
    path('education/', views.EducationAjaxView.as_view(), name="education-ajax"),
    # services list url
    path('services/', views.ServicesListView.as_view(), name="service-list"),
    # services detail url
    re_path(r'^services/(?P<slug>.*)/$', views.ServicesDetailView.as_view(), name="service-detail"),
    # news List url
    path('news-list/', views.NewsListView.as_view(), name="news-list"),
    # blog List url
    path('blog-list/', views.BlogListView.as_view(), name="blog-list"),

    # video List url
    path('video-list/', views.VideoListView.as_view(), name="video-list"),
    # video detail url
    re_path(r'^video-detail/(?P<slug>.*)/$', views.VideoDetailView.as_view(), name="video-detail"),
    #faqadd
    path('faq/', views.faqView.as_view(), name="news-list"),
    # news detail url
    re_path(r'^news-detail/(?P<slug>.*)/$', views.NewsDetailView.as_view(), name="news-detail"),
    # news detail url
    re_path(r'^blog-detail/(?P<slug>.*)/$', views.BlogDetailView.as_view(), name="blog-detail"),
    # review List url
    path('reviews/', views.ReviewListView.as_view(), name="review-list"),
    # review detail url
    re_path(r'^reviews/(?P<slug>.*)/$', views.ReviewDetailView.as_view(), name="review-detail"),
    # Main page contact form
    path('contact/us/', views.CountactUsFormView.as_view(), name="consultant-form"),
    # event list page
    path('events/', views.EventListView.as_view(), name="event-list"),
    # event arcive detail view
    path('special-events/', views.ApplyView.as_view(), name="special-events"),
    re_path(r'^events/(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/$', views.EventArcihveView.as_view(), name="event-archive"),
    # event arcive detail view
    path('reserve/', views.ReserveDateView.as_view(), name="reserve-date"),
    path('reserve/country-universities/', views.ReserveCountryUniAjaxView.as_view(),
        name="reserve-country-universities"),
    re_path(r'^reserve/(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/$', views.ReserveSaveDateView.as_view(), name="reserve-save-date"),
    # event detail page
    re_path(r'^events/(?P<slug>.*)/$', views.EventDetailView.as_view(), name="event-detail"),
    # education country detail View
    path('countries/<slug:country_slug>/<slug:education_slug>/', views.CounrtyEducationListView.as_view(), name="country-search-view"),
    # education detail View
    re_path(r'^countries/(?P<country_slug>[-\w]+)/(?P<education_slug>[-\w]+)/(?P<slug>.*)/$', views.UnivercityDetailView.as_view(), name="univercity-detail"),
    # programs page
    path('programs/', views.ProgramsView.as_view(), name="program-list"),
    path('report/', DataAnalysis.as_view(), name='data_analysis'),
    # ajax views
    path('searchforms/', views.SearchFormView.as_view(), name="search-form"),
    path('educationforms/', views.EducationSearchForm.as_view(), name="education-search-form"),
    path('contactform/', views.EducationContactView.as_view(), name="contact-us-ajax"),
    path('countrycity/', views.GetContyCityView.as_view(), name="contact-city-ajax"),
    # testing issues
    # url(r'^testing/$', views.TestingView.as_view(), name="testing"),
    path('successful/', views.SuccessfulView.as_view(), name="successful"),
    path('done/', views.ReserveSuccessfulView.as_view(), name="done"),
    re_path(r'^exhibitions/(?P<slug>.*)/$', views.ExhibitionDetails.as_view(), name="exhibition"),
    # insurance
    path('pasha-insurance/', InsuranceView.as_view(), name="insurance"),
    # Main page contact form
    re_path(r'^(?P<slug>.*)/$', views.EducationCategoryListView.as_view(), name="education-list"),
]

backend_azeri_student/student/models.py
import datetime
from urllib.parse import urlparse

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe

from student.options.fields import GoogleMapField, YoutubeLinkField
from student.options.tools import get_slider_image, get_country_icon, get_country_cover, get_about_cover, REVIEW_TYPE, \
    CONTENT_TYPE, AGE_RESTRICTION, SEASON, EVENT_TEMPLATE, get_successful_cover, get_exhibition_cover_path, \
    get_participant_image_path, EXHIBITION_CONTENT_TYPE, RESERVE_CITY , INSURANCE_CONTENT_TYPE, get_apply_image, get_apply_cover_image
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
##############################################################################
# <<<<<<<<<<<<<<<<<<<<<<<<<<< Website Common Settings <<<<<<<<<<<<<<<<<<<<<<<#
##############################################################################


class WebsiteSetings(models.Model):
    """
        WebsiteSettings main model
        All website settings and
        configuration make this model
    """
    # html <head> section settings here
    robots = models.CharField(max_length=255,
                              default="noindex",
                              help_text="index, follow")
    keywords = models.CharField(max_length=255,
                                default="Xaricdə Təhsil, təhsil, universitetlər, ölkələr",
                                help_text="hər bir sözü `,`-vergül ilə ayırın")
    description = models.TextField(default="2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, "
                                           "Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.",
                                   help_text="sayt haqqında məlumat")
    website_title = models.CharField(max_length=255,
                                     default="AzeriStudent",
                                     help_text="Saytin adı")

    search_title = models.CharField(max_length=255,
                                    default="560 training programs in 21 countries - choose what is right for you")

    services_title = models.CharField(max_length=255,
                                      default="Our services")
    services_image = models.ImageField(upload_to=get_country_cover,
                                       null=True, blank=True)
    news_title = models.CharField(max_length=255,
                                  default="Xəbərlər")
    blog_title = models.CharField(max_length=255,
                                  default="Blog yazıları")
    
    video_title = models.CharField(max_length=255,
                                  default="Videolar")
    
    about_title = models.CharField(max_length=255,
                                   default="Why choose study abroad")
    content = RichTextUploadingField(null=True, blank=True, default="<p>Text</p>")

    review_title = models.CharField(max_length=255,
                                    default="Rəylər")
    review_cover = models.ImageField(null=True, blank=True, upload_to=get_about_cover)

    successful_cover = models.ImageField(null=True, blank=True, upload_to=get_successful_cover)

    uni_logo_count   = models.IntegerField(default=5)
    ## contunied
    # social headers
    meta_keywords = models.CharField(max_length=300, editable=False,
                                     default="Azeristudent | You study, we care!")
    meta_description = models.TextField(editable=False,
                                        default="2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.")
    social_image = models.ImageField(upload_to=get_country_cover, null=True, blank=True)
    facebook_social_title = models.CharField(max_length=255, default="Azeristudent | You study, we care!")
    facebook_social_description = models.CharField(max_length=255,
                                                   default="2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.")
    twitter_social_image_alt = models.CharField(max_length=255,
                                                default="2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.")
    twitter_social_creator = models.CharField(max_length=255, default="@azeristudent01")
    twitter_social_site = models.CharField(max_length=255, default="@azeristudent01")

    # reservation
    reservation_count = models.PositiveIntegerField('Reservation Count', null=True, blank=True)
    
    faq_cover_image     = models.ImageField(null = True,blank=True,upload_to = 'faq-cover')

    def __str__(self):
        return "{}".format("Saytın tənzimləmələri")

    def get_review_cover(self):
        if self.review_cover:
            return self.review_cover.url
        else:
            return

    def get_services_cover(self):
        if self.services_image:
            return self.services_image.url
        else:
            return ""


##############################################################################
# <<<<<<<<<<<<<<<<<<<<<<<<<<< Website Main page menu  <<<<<<<<<<<<<<<<<<<<<<<#
##############################################################################
class ProgramMenu(models.Model):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=255, help_text="Example /about/ -page url")
    order = models.IntegerField(default=0)
    menu = models.ForeignKey('MainMenu', on_delete=models.CASCADE)
    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        ordering = ("order",)


class MainMenu(models.Model):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=255, help_text="Example /about/ -page url")
    order = models.IntegerField(default=0)
    target_blank = models.BooleanField(default=False)
    dropdown = models.BooleanField(default=False)
    muraciet_button = models.BooleanField(default=False)
    status = models.BooleanField(default=True)
    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        ordering = ('order',)


class BaseSlider(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    desription = models.CharField(max_length=255, null=True, blank=True)
    button_text = models.CharField(max_length=255, default="Ətraflı")
    button_link = models.CharField(max_length=255, null=True, blank=True)
    background_image = models.ImageField(upload_to=get_slider_image)
    status = models.BooleanField(default=True)

    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s - Slider" % self.title

    def get_slider_img(self):
        if self.background_image:
            return mark_safe("<img src='%s' style='width: 300px; height:auto' />" % self.background_image.url)
        else:
            return mark_safe(
                "<img src='%s' style='width: 300px; height:auto' />" % "https://totemmaker.net/wp-content/themes/theme/img/img-not-found.jpg")

    get_slider_img.short_description = 'Slayder şəkli'
    get_slider_img.allow_tags = True

    class Meta:
        ordering = ('-id',)


class CostOfEducation(models.Model):
    name = models.CharField(max_length=255)
    country = models.ForeignKey('Country', on_delete=models.CASCADE)
    price = models.CharField(max_length=255)
    context = RichTextUploadingField(verbose_name="Siyahı")

    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {}".format(self.name, self.price)


class Country(models.Model):
    # menu link country
    name = models.CharField(max_length=255)
    icon = models.ImageField(upload_to=get_country_icon)
    order = models.IntegerField(default=0,
                                verbose_name="Sırası")
    # content inside country
    title = models.CharField(max_length=255,
                             verbose_name="Başlıq")
    background_image = models.ImageField(upload_to=get_country_cover)
    about = RichTextUploadingField(null=True, blank=True,
                                   verbose_name="Ölkə haqqında")
    prospect = RichTextUploadingField(null=True, blank=True,
                                      verbose_name="Persperktləri")
    expert = RichTextUploadingField(null=True, blank=True,
                                    verbose_name="Expert help")
    # Cost of education in Country

    # country slug
    slug = models.SlugField(null=True, blank=True)
    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.name)

    def get_absolute_url(self):
        return reverse("country-detail", kwargs={'slug': self.slug})

    def get_higher_education(self):
        return self.education_set.filter(education_type__id=1).last()

    def get_secondary_education(self):
        return self.education_set.filter(education_type__id=2).last()

    def get_language_program(self):
        return self.education_set.filter(education_type__id=3).last()

    class Meta:
        ordering = ('order',)


class AltMenuAboutUs(models.Model):
    name = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255)
    url = models.CharField(max_length=255, help_text="Example /about/ -page url")
    order = models.IntegerField(default=0)
    about = models.ForeignKey('AboutUs', on_delete=models.CASCADE)

backend_azeri_student/student/templates/education/partials/pagination.html
{% load static %}
{% if is_paginated %}
    <div class="pagination-wrap">
        <div class="pagination-nav">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="back"><img
                        src="{% static 'azeristudent/img/left-arrow.png' %}" alt="">Geriyə</a>
            {% endif %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="next">Növbəti<img
                        src="{% static 'azeristudent/img/right-arrow.png' %}" alt=""></a>
            {% endif %}
        </div>
        <ul class="pagination">
            <!-- {% if not page_range %}
                {% for page_number in paginator.page_range %}
                    {% if page_number == page_obj.number %}
                        <li class="active">
                            <a>{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            {% else %}
                {% for page_number in page_range %}
                    {% if page_number == page_obj.number %}
                        <li class="active">
                            <a>{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            {% endif %} -->
            {% if page_obj.number >= 5 %}
            <li><a href="?page=1">1</a></li>
            <li><a href="javascript:void()" style="pointer-events: none;">...</a></li>
            {% elif page_obj.number == 4 %}
            <li><a href="?page=1">1</a></li>
            {% endif %}
            {% if page_obj.number|add:"-2" >= 1  %}
            <li><a href="?page={{ page_obj.number|add:"-2" }}">{{ page_obj.number|add:"-2" }}</a></li>
            {% endif %}
            {% if page_obj.number|add:"-1" >= 1  %}
            <li><a href="?page={{ page_obj.number|add:"-1" }}">{{ page_obj.number|add:"-1" }}</a></li>
            {% endif %}
            <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
            {% if page_obj.number|add:"1" <= paginator.num_pages  %}
            <li><a href="?page={{ page_obj.number|add:"1" }}">{{ page_obj.number|add:"1" }}</a></li>
            {% endif %}
            {% if page_obj.number|add:"2" <= paginator.num_pages %}
            <li><a href="?page={{ page_obj.number|add:"2" }}">{{ page_obj.number|add:"2" }}</a></li>
            {% endif %}
            {% if page_obj.number|add:"2" <= paginator.num_pages|add:"-2" %}
            <li><a href="javascript:void()" style="pointer-events: none;">...</a></li>
            <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
            {% elif page_obj.number|add:"1" <= paginator.num_pages|add:"-2" %}
            <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
            {% endif %}
        </ul>
    </div>
{% endif %}

backend_azeri_student/student/templates/education/partials/search.html
{% if education_type == 1 %}
    <div class="form-select">
        <select name="country" id="id_country">
            {% if country_name %}
                <option value="{{ country_name.pk }}" selected>{{ country_name.name }}</option>
            {% else %}
                <option value="">Ölkələr</option>
            {% endif %}
            {% for country in country_list %}
                <option value="{{ country.pk }}">{{ country.name }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-select">
        <select name="univercity_program" id="id_univercity_program">
            <option value="" selected="">Universitet proqramı</option>
            {% for prog in univercity_program %}
                <option value="{{ prog.pk }}">{{ prog.name }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-select">
        <select name="specials" id="id_specials">
            <option value="">Xüsusiyyətləri</option>
            {% for spec in special %}
                <option value="{{ spec.pk }}">{{ spec.name }}</option>
            {% endfor %}

        </select>
    </div>

    <div class="form-select">
        <select name="language" id="id_language">
            <option value="">Dil</option>
            {% for lang in language %}
                <option value="{{ lang.pk }}">{{ lang.name }}</option>
            {% endfor %}

        </select>
    </div>

    <div class="form-select">
        <select name="city" id="id_city">
            <option value="" selected="">Şəhər</option>
            {% for city in city_list %}
                <option value="{{ city.pk }}">{{ city.name }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-select">
        <select name="school_type" id="id_school_type">
            <option value="" selected="">Universitetin tipi</option>
            {% for type in scool_type %}
                <option value="{{ type.pk }}">{{ type.name }}</option>
            {% endfor %}
        </select>
    </div>
{% elif education_type == 2 %}
    <div class="form-select">
        <select name="country" required="" id="id_country">
           {% if country_name %}
                <option value="{{ country_name.pk }}" selected>{{ country_name.name }}</option>
            {% else %}
                <option value="">Ölkələr</option>
            {% endif %}
            {% for country in country_list %}
                <option value="{{ country.pk }}">{{ country.name }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-select">
        <input type="text" placeholder="Yaş" name="yaş">
    </div>

    <div class="form-select">
        <select name="programs" id="id_programs">
            <option value="">Proqramlar</option>
            {% for prog in secondary_program %}
                <option value="{{ prog.pk }}">{{ prog.name }}</option>
            {% endfor %}

        </select>
    </div>

    <div class="form-select">
        <select name="language" id="id_language">
            <option value="">Dil</option>
            {% for lang in language %}
                <option value="{{ lang.pk }}">{{ lang.name }}</option>
            {% endfor %}

        </select>
    </div>

    <div class="form-select">
        <select name="school_type" id="id_school_type">
            <option value="" selected="">Məktəbin tipi</option>
            {% for type in scool_type %}
                <option value="{{ type.pk }}">{{ type.name }}</option>
            {% endfor %}
        </select>
    </div>
{% else %}
    <div class="form-select">
        <select name="country" required="" id="id_country">
            {% if country_name %}
                <option value="{{ country_name.pk }}" selected>{{ country_name.name }}</option>
            {% else %}
                <option value="">Ölkələr</option>
            {% endif %}
            {% for country in country_list %}
                <option value="{{ country.pk }}">{{ country.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-select">
        <select name="language" id="id_language">
            <option value="">Dil</option>
            {% for lang in language %}
                <option value="{{ lang.pk }}">{{ lang.name }}</option>
            {% endfor %}

        </select>
    </div>
    <div class="form-select">
        <select name="age_restriction" id="id_age_restriction">
            <option value="">Yaş məhdudiyyəti</option>
            {% for age in age_restriction %}
                <option value="{{ age.0 }}">{{ age.1 }}</option>
            {% endfor %}

        </select>
    </div>
    <div class="form-select">
        <input type="text" placeholder="Yaş" name="yaş">
    </div>
    <div class="form-select">
        <select name="season" id="id_season">
            <option value="">Fəsil</option>
            {% for s in season %}
                <option value="{{ s.0 }}">{{ s.1 }}</option>
            {% endfor %}

        </select>
    </div>
    <div class="form-select">
        <select name="program" id="id_program">
            <option value="">Proqramlar</option>
            {% for lang in lang_programs %}
                <option value="{{ lang.pk }}">{{ lang.name }}</option>
            {% endfor %}

        </select>
    </div>

    <div class="form-select">
        <select name="program" id="id_program">
            <option value="">Ərazi</option>
            {% for accom in accomondation %}
                <option value="{{ accom.pk }}">{{ accom.name }}</option>
            {% endfor %}

        </select>
    </div>

{% endif %}
<button type="submit" class="btn find-btn">Axtar</button>