backend_azeri_student/azeri/urls.py
import os
from django.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls.i18n import i18n_patterns  # for url translation
# from oscar.app import application # oscar applications urls here
from django.views.generic import TemplateView
from django.conf.urls import handler404, handler500
from student import views as student_views
from django.urls import path, re_path

admin.autodiscover()

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('labmin/', admin.site.urls),
    path('ckeditor/', include("ckeditor_uploader.urls")),
    path('page/', include('flatpages.urls')),
    path('faqapi/', include('student.api.urls',namespace='faqapi')),
    #url(r'^api-auth/', include('rest_framework.urls')),

    # url(r'^', include("student.urls")),
    # url(r'^', include("partners.urls")),
]

urlpatterns += [
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name="azeri/robots.txt", content_type='text/plain')),
]


if os.environ.get('PARTNER_PAGE') == "true":
    urlpatterns += [
        path('', include("partners.urls"))
    ]
else:
    urlpatterns += [
        path('', include("student.urls"))
    ]

# urlpatterns += i18n_patterns(
#     url(r'^', include("student.urls")),
#     url(r'^', application.urls),
#     url(r'^page/', include('django.contrib.flatpages.urls')),
# )

handler404 = student_views.error_404
handler500 = student_views.error_500

# in development django built-in server serves static and media content 
if not settings.PROD:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# This is change default admin panel Headers and titles
admin.site.site_header = 'AzeriStudent Admin'
admin.site.site_title = 'AzeriStudent Administration'
admin.site.index_title = 'AzeriStudent Administration'

backend_azeri_student/student/api/urls.py
from django.urls import include
from .views import *
from django.urls import path

app_name='faqapi'
urlpatterns = [
    path('question-type/', FaqQuestionTypeView.as_view(), name = 'question type'),
    path('questions/', FaqQuestionView.as_view(), name = 'question'),
]

backend_azeri_student/student/urls.py
from django.contrib.auth.decorators import permission_required
from django.contrib.sitemaps.views import sitemap

from partners.views import DataAnalysis
from student.sitemaps import *
from student.views import InsuranceView
from . import views
from django.urls import path, re_path

sitemaps = {
    'home': BaseIndexSitemap,
    'about': AboutPageSitemap,
    'country': CountryDetailSitemap,
    'services': ServicesListSitemap,
    'service': ServicesDetailSitemap,
    'news': NewsListSitemap,
    'new': NewsDetailSitemap,
    'blogs': BlogListSitemap,
    'blog':  BlogDetailSitemap,
    'reviews': ReviewListSitemap,
    'review': ReviewDetailSitemap,
    'events': EventListSitemap,
    'event': EventDetailSitemap,
    'reserve': ReserveDateSitemap,
    'university': UniversityDetailSitemap,
    'programs': ProgramsListSitemap,
    'exhibition': ExhibitionDetailSitemap,
    'insurance': InsuranceSitemap,
    'education-category-list': EducationCategoryListSitemap,
}


urlpatterns = [
    # main page home
    path('', views.BaseIndexView.as_view(), name="index"),
    re_path(r'^sitemap\.xml/$', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    # about page
    path('about/', views.AboutPageView.as_view(), name="about-us"),
    # country detail page
    path('countries/<slug:slug>/', views.CountryDetailView.as_view(), name="country-detail"),
    # ajax urls here
    path('education/', views.EducationAjaxView.as_view(), name="education-ajax"),
    # services list url
    path('services/', views.ServicesListView.as_view(), name="service-list"),
    # services detail url
    re_path(r'^services/(?P<slug>.*)/$', views.ServicesDetailView.as_view(), name="service-detail"),
    # news List url
    path('news-list/', views.NewsListView.as_view(), name="news-list"),
    # blog List url
    path('blog-list/', views.BlogListView.as_view(), name="blog-list"),

    # video List url
    path('video-list/', views.VideoListView.as_view(), name="video-list"),
    # video detail url
    re_path(r'^video-detail/(?P<slug>.*)/$', views.VideoDetailView.as_view(), name="video-detail"),
    #faqadd
    path('faq/', views.faqView.as_view(), name="news-list"),
    # news detail url
    re_path(r'^news-detail/(?P<slug>.*)/$', views.NewsDetailView.as_view(), name="news-detail"),
    # news detail url
    re_path(r'^blog-detail/(?P<slug>.*)/$', views.BlogDetailView.as_view(), name="blog-detail"),
    # review List url
    path('reviews/', views.ReviewListView.as_view(), name="review-list"),
    # review detail url
    re_path(r'^reviews/(?P<slug>.*)/$', views.ReviewDetailView.as_view(), name="review-detail"),
    # Main page contact form
    path('contact/us/', views.CountactUsFormView.as_view(), name="consultant-form"),
    # event list page
    path('events/', views.EventListView.as_view(), name="event-list"),
    # event arcive detail view
    path('special-events/', views.ApplyView.as_view(), name="special-events"),
    re_path(r'^events/(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/$', views.EventArcihveView.as_view(), name="event-archive"),
    # event arcive detail view
    path('reserve/', views.ReserveDateView.as_view(), name="reserve-date"),
    path('reserve/country-universities/', views.ReserveCountryUniAjaxView.as_view(),
        name="reserve-country-universities"),
    re_path(r'^reserve/(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/$', views.ReserveSaveDateView.as_view(), name="reserve-save-date"),
    # event detail page
    re_path(r'^events/(?P<slug>.*)/$', views.EventDetailView.as_view(), name="event-detail"),
    # education country detail View
    path('countries/<slug:country_slug>/<slug:education_slug>/', views.CounrtyEducationListView.as_view(), name="country-search-view"),
    # education detail View
    re_path(r'^countries/(?P<country_slug>[-\w]+)/(?P<education_slug>[-\w]+)/(?P<slug>.*)/$', views.UnivercityDetailView.as_view(), name="univercity-detail"),
    # programs page
    path('programs/', views.ProgramsView.as_view(), name="program-list"),
    path('report/', DataAnalysis.as_view(), name='data_analysis'),
    # ajax views
    path('searchforms/', views.SearchFormView.as_view(), name="search-form"),
    path('educationforms/', views.EducationSearchForm.as_view(), name="education-search-form"),
    path('contactform/', views.EducationContactView.as_view(), name="contact-us-ajax"),
    path('countrycity/', views.GetContyCityView.as_view(), name="contact-city-ajax"),
    # testing issues
    # url(r'^testing/$', views.TestingView.as_view(), name="testing"),
    path('successful/', views.SuccessfulView.as_view(), name="successful"),
    path('done/', views.ReserveSuccessfulView.as_view(), name="done"),
    re_path(r'^exhibitions/(?P<slug>.*)/$', views.ExhibitionDetails.as_view(), name="exhibition"),
    # insurance
    path('pasha-insurance/', InsuranceView.as_view(), name="insurance"),
    # Main page contact form
    re_path(r'^(?P<slug>.*)/$', views.EducationCategoryListView.as_view(), name="education-list"),
]

backend_azeri_student/student/models.py
import datetime
from urllib.parse import urlparse

from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe

from student.options.fields import GoogleMapField, YoutubeLinkField
from student.options.tools import get_slider_image, get_country_icon, get_country_cover, get_about_cover, REVIEW_TYPE, \
    CONTENT_TYPE, AGE_RESTRICTION, SEASON, EVENT_TEMPLATE, get_successful_cover, get_exhibition_cover_path, \
    get_participant_image_path, EXHIBITION_CONTENT_TYPE, RESERVE_CITY , INSURANCE_CONTENT_TYPE, get_apply_image, get_apply_cover_image
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
##############################################################################
# <<<<<<<<<<<<<<<<<<<<<<<<<<< Website Common Settings <<<<<<<<<<<<<<<<<<<<<<<#
##############################################################################


class WebsiteSetings(models.Model):
    """
        WebsiteSettings main model
        All website settings and
        configuration make this model
    """
    # html <head> section settings here
    robots = models.CharField(max_length=255,
                              default="noindex",
                              help_text="index, follow")
    keywords = models.CharField(max_length=255,
                                default="Xaricdə Təhsil, təhsil, universitetlər, ölkələr",
                                help_text="hər bir sözü `,`-vergül ilə ayırın")
    description = models.TextField(default="2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, "
                                           "Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.",
                                   help_text="sayt haqqında məlumat")
    website_title = models.CharField(max_length=255,
                                     default="AzeriStudent",
                                     help_text="Saytin adı")

    search_title = models.CharField(max_length=255,
                                    default="560 training programs in 21 countries - choose what is right for you")

    services_title = models.CharField(max_length=255,
                                      default="Our services")
    services_image = models.ImageField(upload_to=get_country_cover,
                                       null=True, blank=True)
    news_title = models.CharField(max_length=255,
                                  default="Xəbərlər")
    blog_title = models.CharField(max_length=255,
                                  default="Blog yazıları")
    
    video_title = models.CharField(max_length=255,
                                  default="Videolar")
    
    about_title = models.CharField(max_length=255,
                                   default="Why choose study abroad")
    content = RichTextUploadingField(null=True, blank=True, default="<p>Text</p>")

    review_title = models.CharField(max_length=255,
                                    default="Rəylər")
    review_cover = models.ImageField(null=True, blank=True, upload_to=get_about_cover)

    successful_cover = models.ImageField(null=True, blank=True, upload_to=get_successful_cover)

    uni_logo_count   = models.IntegerField(default=5)
    ## contunied
    # social headers
    meta_keywords = models.CharField(max_length=300, editable=False,
                                     default="Azeristudent | You study, we care!")
    meta_description = models.TextField(editable=False,
                                        default="2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.")
    social_image = models.ImageField(upload_to=get_country_cover, null=True, blank=True)
    facebook_social_title = models.CharField(max_length=255, default="Azeristudent | You study, we care!")
    facebook_social_description = models.CharField(max_length=255,
                                                   default="2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.")
    twitter_social_image_alt = models.CharField(max_length=255,
                                                default="2008- ci ildən fəaliyyətə başlayan, 10 il iş təcrübəsinə malik, Azərbaycanın ən güvənilən xaricdə təhsil agentliyiyik.")
    twitter_social_creator = models.CharField(max_length=255, default="@azeristudent01")
    twitter_social_site = models.CharField(max_length=255, default="@azeristudent01")

    # reservation
    reservation_count = models.PositiveIntegerField('Reservation Count', null=True, blank=True)
    
    faq_cover_image     = models.ImageField(null = True,blank=True,upload_to = 'faq-cover')

    def __str__(self):
        return "{}".format("Saytın tənzimləmələri")

    def get_review_cover(self):
        if self.review_cover:
            return self.review_cover.url
        else:
            return

    def get_services_cover(self):
        if self.services_image:
            return self.services_image.url
        else:
            return ""


##############################################################################
# <<<<<<<<<<<<<<<<<<<<<<<<<<< Website Main page menu  <<<<<<<<<<<<<<<<<<<<<<<#
##############################################################################
class ProgramMenu(models.Model):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=255, help_text="Example /about/ -page url")
    order = models.IntegerField(default=0)
    menu = models.ForeignKey('MainMenu', on_delete=models.CASCADE)
    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        ordering = ("order",)


class MainMenu(models.Model):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=255, help_text="Example /about/ -page url")
    order = models.IntegerField(default=0)
    target_blank = models.BooleanField(default=False)
    dropdown = models.BooleanField(default=False)
    muraciet_button = models.BooleanField(default=False)
    status = models.BooleanField(default=True)
    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        ordering = ('order',)


class BaseSlider(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    desription = models.CharField(max_length=255, null=True, blank=True)
    button_text = models.CharField(max_length=255, default="Ətraflı")
    button_link = models.CharField(max_length=255, null=True, blank=True)
    background_image = models.ImageField(upload_to=get_slider_image)
    status = models.BooleanField(default=True)

    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s - Slider" % self.title

    def get_slider_img(self):
        if self.background_image:
            return mark_safe("<img src='%s' style='width: 300px; height:auto' />" % self.background_image.url)
        else:
            return mark_safe(
                "<img src='%s' style='width: 300px; height:auto' />" % "https://totemmaker.net/wp-content/themes/theme/img/img-not-found.jpg")

    get_slider_img.short_description = 'Slayder şəkli'
    get_slider_img.allow_tags = True

    class Meta:
        ordering = ('-id',)


class CostOfEducation(models.Model):
    name = models.CharField(max_length=255)
    country = models.ForeignKey('Country', on_delete=models.CASCADE)
    price = models.CharField(max_length=255)
    context = RichTextUploadingField(verbose_name="Siyahı")

    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {}".format(self.name, self.price)


class Country(models.Model):
    # menu link country
    name = models.CharField(max_length=255)
    icon = models.ImageField(upload_to=get_country_icon)
    order = models.IntegerField(default=0,
                                verbose_name="Sırası")
    # content inside country
    title = models.CharField(max_length=255,
                             verbose_name="Başlıq")
    background_image = models.ImageField(upload_to=get_country_cover)
    about = RichTextUploadingField(null=True, blank=True,
                                   verbose_name="Ölkə haqqında")
    prospect = RichTextUploadingField(null=True, blank=True,
                                      verbose_name="Persperktləri")
    expert = RichTextUploadingField(null=True, blank=True,
                                    verbose_name="Expert help")
    # Cost of education in Country

    # country slug
    slug = models.SlugField(null=True, blank=True)
    # logs
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.name)

    def get_absolute_url(self):
        return reverse("country-detail", kwargs={'slug': self.slug})

    def get_higher_education(self):
        return self.education_set.filter(education_type__id=1).last()

    def get_secondary_education(self):
        return self.education_set.filter(education_type__id=2).last()

    def get_language_program(self):
        return self.education_set.filter(education_type__id=3).last()

    class Meta:
        ordering = ('order',)


class AltMenuAboutUs(models.Model):
    name = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255)
    url = models.CharField(max_length=255, help_text="Example /about/ -page url")
    order = models.IntegerField(default=0)
    about = models.ForeignKey('AboutUs', on_delete=models.CASCADE)

backend_azeri_student/student/templates/countries/detail.html
{% extends "home/index.html" %}
{% load static %}
{% block title %}
    {{ object.title }} | {{ block.super }}
{% endblock %}

{% block social_headers %}
    <!-- Facebook share header -->
    <meta property="og:title" content="{{ object.title }}">
    <meta property="og:description" content="{{ object.about|safe|cut:"<p>"|cut:"</p>" }}">
    {% if object.background_image %}
        <meta property="og:image"
              content="{{ object.background_image.url }}">
    {% endif %}
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <!--Twitter header-->
    <meta name="twitter:card" content="summary_large_image">
    {% if object.background_image %}
        <meta name="twitter:image"
              content="https://{{ request.get_host }}{{ object.background_image.url }}">
    {% endif %}
    <meta name="twitter:image:alt" content="{{ object.title }}">
    <meta name="twitter:creator" content="@azeristudent01"/>
    <meta name="twitter:site" content="@azeristudent01">
{% endblock %}
{{% block extra_script %}
<!-- Facebook Pixel Code -->
<script> 
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window, document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '3029457137373275');
    fbq('track', 'PageView');
    fbq('track', 'ViewContent',{
        content_name: '{{ object.title }}',
        content_category: 'Countries',
    });
    </script>
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=3029457137373275&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Facebook Pixel Code -->
    
{% endblock %}

{% block base_content %}
    <section class="study-page">
        <div class="page-cover" style="background-image:url({{ object.background_image.url }})">
            <div class="container">
                <div class="cover-items">
                    <h1 class="page-title ">{{ object.title }}</h1>
                    <ol class="breadcrumb ">
{#                        <li class="breadcrumb-item"><a href="{% url 'index' %}">Ana səhifə</a></li>#}
                        <li class="breadcrumb-item"><a href="{% url 'index' %}">AzeriStudent</a></li>
                        <li class="breadcrumb-item active" aria-current="page"> {{ object.title }}</li>
                    </ol>
                    <p class="cover-info "></p>
                </div>
            </div>
        </div>

        <div class="study-wrap">
            <div class="container">
                <div class="study-section">
                    <div class="heading">
                        <h1>Ölkə haqqında</h1>
                    </div>
                    <div class="about-country study">
                        <div class="country-left">
                            {{ object.about|safe }}
                        </div>
                        <div class="country-right">
                            <ul>
                                {% if object.get_higher_education %}
                                    <li>
                                        <a href="{% url 'country-search-view' country_slug=object.get_higher_education.country.slug education_slug=object.get_higher_education.education_type.slug %}">{{ object.get_higher_education.education_type.title }}
                                            <img src="{% static 'azeristudent/img/right-arrow.png' %}" alt=""></a>
                                    </li>
                                {% endif %}
                                {% if object.get_secondary_education %}
                                    <li>
                                        <a href="{% url 'country-search-view' country_slug=object.get_secondary_education.country.slug education_slug=object.get_secondary_education.education_type.slug %}">{{ object.get_secondary_education.education_type.title }}
                                            <img src="{% static 'azeristudent/img/right-arrow.png' %}" alt=""></a>
                                    </li>
                                {% endif %}
                                {% if object.get_language_program %}
                                    <li>
                                        <a href="{% url 'country-search-view' country_slug=object.get_language_program.country.slug education_slug=object.get_language_program.education_type.slug %}">{{ object.get_language_program.education_type.title }}
                                            <img src="{% static 'azeristudent/img/right-arrow.png' %}" alt=""></a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    <div class="prospects study">
                        {{ object.prospect|safe }}
                    </div>

                </div>
            </div>
            <div class="expert study">
                <div class="container">
                    {{ object.expert|safe }}
                </div>
            </div>
        </div>

        <div class="container">
            <div class="studying-programs-wrap">
                <div class="page-title"><h1>Təhsil proqramları</h1></div>
                {% for program in object.education_set.all|slice:":2" %}
                    <a href="{{ program.get_absolute_url }}">
                        <div class="program-item">
                            <div class="program-img" style="background-image:url({{ program.cover_img.url }})"></div>
                            <div class="program-info">
                                <h2 class="title">{{ program.title }}</h2>
                                <p class="content">
                                    {{ program.summary|safe }}
                                </p>
                                <div class="see-link">
                                    <div>Daha ətraflı <img src="{% static 'azeristudent/img/right-arrow.png' %}"/></div>
                                </div>
                            </div>
                        </div>
                    </a>
                {% empty %}
                    <div>Təhsil programi yoxdur</div>
                {% endfor %}
            </div>
        </div>

        {#        EDIT#}
        <div id="country_study_type_icon">
            <div class="container">
                <div class="flex-row">
                    {% if object.get_higher_education %}
                        <div class="flex-item">
                            <a href="{% url 'country-search-view' country_slug=object.get_higher_education.country.slug education_slug=object.get_higher_education.education_type.slug %}"
                               class="content">
                                <div class="imgHolder">
                                    <img src="{% static 'azeristudent/img/Asset 4.svg' %}" alt="">
                                    <img src="{% static 'azeristudent/img/Asset 4 hover.svg' %}" alt="">
                                </div>

                                <h5>Bütün {{ object.get_higher_education.education_type.title|lower }}</h5>
                            </a>
                        </div>
                    {% endif %}
                    {% if object.get_secondary_education %}
                        <div class="flex-item">
                            <a href="{% url 'country-search-view' country_slug=object.get_secondary_education.country.slug education_slug=object.get_secondary_education.education_type.slug %}"
                               class="content">
                                <div class="imgHolder">
                                    <img src="{% static 'azeristudent/img/Asset 3.svg' %}" alt="">
                                    <img src="{% static 'azeristudent/img/Asset 3 hover.svg' %}" alt="">
                                </div>

                                <h5>Bütün {{ object.get_secondary_education.education_type.title |lower}}</h5>
                            </a>
                        </div>
                    {% endif %}
                    {% if object.get_language_program %}
                        <div class="flex-item">
                            <a href="{% url 'country-search-view' country_slug=object.get_language_program.country.slug education_slug=object.get_language_program.education_type.slug %}"
                               class="content">
                                <div class="imgHolder">
                                    <img src="{% static 'azeristudent/img/Asset 2.svg' %}" alt="">
                                    <img src="{% static 'azeristudent/img/Asset 2 hover.svg' %}" alt="">
                                </div>

                                <h5>Bütün {{ object.get_language_program.education_type.title|lower }}</h5>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {#END OF EDIT#}


        <div class="cost section">
            <div class="container">
                <div class="page-title">
                    <h1>{{ object.title }} xərcləri</h1>
                </div>
                <div class="cost-heading data-custom-tab">
                    {% for cost in object.costofeducation_set.all %}
                        <h3 data-toggle="tab" data-href="#{{ cost.name|slugify }}"
                            {% if forloop.first %}class="active"{% endif %}>{{ cost.name }}</h3>
                    {% endfor %}
                </div>
                {% for cost in object.costofeducation_set.all %}
                    <div id="{{ cost.name|slugify }}" class="data-tab-item"
                         {% if not forloop.first %}style="display: none"{% endif %}>
                        {{ cost.context|safe }}
                    </div>
                {% endfor %}

            </div>

        </div>
        {% include "partials/social_media_buttons.html" %}
        <div class="container">
            {% include "partials/do_with_us.html" %}
        </div>
    </section>
{% endblock %}